spring.application.name=url-shortener-with-consistent-hashing
spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener
spring.datasource.username=postgres
spring.datasource.password=pg12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Spring boot now knows the Redis server location which is localhost:6379
spring.data.redis.host=localhost
spring.data.redis.port=6379