spring.application.name=url-shortener-with-consistent-hashing
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#Spring boot now knows the Redis server location which is localhost:6379
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true