spring.application.name=url-shortener-with-consistent-hashing
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#Spring boot now knows the Redis server location which is localhost:6379
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.demo-seeding.enabled=${DEMO_SEEDING_ENABLED:true}
app.shards.active-count=${ACTIVE_SHARDS_COUNT:3}
app.ratelimit.max-requests=${RATE_LIMIT_MAX_REQUESTS:5}

# HikariCP configuration for serverless database autosuspend (Neon)
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=15000
spring.datasource.hikari.max-lifetime=600000